name: Deploy app files to S3 bucket

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy app files to S3 bucket
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3 # https://github.com/marketplace/actions/checkout

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1 # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy app files to S3 bucket
      run: aws s3 sync ./app/ s3://djfav.ninja --delete # https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html
